<?php

// this php scripts converts the generated changelog from the oracle Database to a more generic Changelog
// the change log is generated by mvn compile -Pliquibase -Ddb=h2totaldiff -Dgoal=generateChangeLog -Dliquibase.changeSetAuthor=diff-script
// usage: php -f fixchangelog.php > output.xml

$filecontent = file_get_contents('target/liquibase/generated.changelog.xml');

// replace NUMBER(3, 0) to tinyint
$filecontent = str_replace("NUMBER(3, 0)", "tinyint", $filecontent);
// replace NUMBER(10, 0) to ints
$filecontent = str_replace("NUMBER(10, 0)", "int", $filecontent);
// replace NUMBER(38, 0) to bigints
$filecontent = str_replace("NUMBER(38, 0)", "bigint", $filecontent);
// replace NUMBER(19, 0) to bigints
$filecontent = str_replace("NUMBER(19, 0)", "bigint", $filecontent);
// replace NUMBER(1, 0) to booleans
$filecontent = str_replace("NUMBER(1, 0)", "boolean", $filecontent);
// replace NUMBER(*, 0) to booleans
$filecontent = str_replace("NUMBER(*, 0)", "boolean", $filecontent);
// replace VARCHAR2(1020 CHAR) to varchar(255)
$filecontent = str_replace("VARCHAR2(1020 CHAR)", "varchar(255)", $filecontent);
// replace VARCHAR2(255 CHAR) to varchar(255)
$filecontent = str_replace("VARCHAR2(255 CHAR)", "varchar(255)", $filecontent);
// replace VARCHAR2(255 CHAR) to varchar(255)
$filecontent = str_replace("VARCHAR2(1024 BYTE)", "varchar(1024)", $filecontent);
// replace VARCHAR2(255 CHAR) to varchar(255)
$filecontent = str_replace("VARCHAR2(255 BYTE)", "varchar(255)", $filecontent);
// replace CLOB to ?
$filecontent = str_replace("CLOB", "clob", $filecontent);
// replace TIMESTAMP to datetime
$filecontent = str_replace('type="TIMESTAMP(6)"', 'type="datetime"', $filecontent);
// replace date to date TODO
$filecontent = str_replace('"date"', '"date"', $filecontent);

// replace 1421231460024 to initial-model
$filecontent = str_replace('1481468384714', 'initial-model', $filecontent);

// catalogName="BTO_XAMW_DEV" baseTableCatalogName="BTO_XAMW_DEV" referencedTableCatalogName="BTO_XAMW_DEV"
$filecontent = str_replace('catalogName="BTO_XAMW_DEV"', '', $filecontent);
$filecontent = str_replace('baseTableCatalogName="BTO_XAMW_DEV"', '', $filecontent);
$filecontent = str_replace('referencedTableCatalogName="BTO_XAMW_DEV"', '', $filecontent);

$filecontent = preg_replace('%forIndexName=\"[^<]*\" %', '', $filecontent);


file_put_contents('target/liquibase/auto.db.changelog-base.xml', $filecontent);

?>