
package ch.mobi.xml.service.ch.mobi.maia.amw.maiaamwfederationservice.v1_0;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaiaAmwFederationService", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/MaiaAmwFederationService/v1_0", wsdlLocation = "file:/home/bschwaller/projects/amw/amw_projects/AMW_maia_federation/src/main/resources/wsdl/ch-mobi-maia-amw-MaiaAmwFederationService-v1.0.wsdl")
public class MaiaAmwFederationService
    extends Service
{

    private final static URL MAIAAMWFEDERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAIAAMWFEDERATIONSERVICE_EXCEPTION;
    private final static QName MAIAAMWFEDERATIONSERVICE_QNAME = new QName("http://xml.mobi.ch/service/ch/mobi/maia/amw/MaiaAmwFederationService/v1_0", "MaiaAmwFederationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/bschwaller/projects/amw/amw_projects/AMW_maia_federation/src/main/resources/wsdl/ch-mobi-maia-amw-MaiaAmwFederationService-v1.0.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAIAAMWFEDERATIONSERVICE_WSDL_LOCATION = url;
        MAIAAMWFEDERATIONSERVICE_EXCEPTION = e;
    }

    public MaiaAmwFederationService() {
        super(__getWsdlLocation(), MAIAAMWFEDERATIONSERVICE_QNAME);
    }

    public MaiaAmwFederationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAIAAMWFEDERATIONSERVICE_QNAME, features);
    }

    public MaiaAmwFederationService(URL wsdlLocation) {
        super(wsdlLocation, MAIAAMWFEDERATIONSERVICE_QNAME);
    }

    public MaiaAmwFederationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAIAAMWFEDERATIONSERVICE_QNAME, features);
    }

    public MaiaAmwFederationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaiaAmwFederationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaiaAmwFederationPortType
     */
    @WebEndpoint(name = "MaiaAmwFederationPort")
    public MaiaAmwFederationPortType getMaiaAmwFederationPort() {
        return super.getPort(new QName("http://xml.mobi.ch/service/ch/mobi/maia/amw/MaiaAmwFederationService/v1_0", "MaiaAmwFederationPort"), MaiaAmwFederationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaiaAmwFederationPortType
     */
    @WebEndpoint(name = "MaiaAmwFederationPort")
    public MaiaAmwFederationPortType getMaiaAmwFederationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xml.mobi.ch/service/ch/mobi/maia/amw/MaiaAmwFederationService/v1_0", "MaiaAmwFederationPort"), MaiaAmwFederationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAIAAMWFEDERATIONSERVICE_EXCEPTION!= null) {
            throw MAIAAMWFEDERATIONSERVICE_EXCEPTION;
        }
        return MAIAAMWFEDERATIONSERVICE_WSDL_LOCATION;
    }

}
