
package ch.mobi.xml.service.ch.mobi.maia.amw.maiaamwfederationservice.v1_0;

import ch.mobi.xml.datatype.ch.mobi.maia.amw.maiaamwfederationservicetypes.v1_0.UpdateRequest;
import ch.mobi.xml.datatype.ch.mobi.maia.amw.maiaamwfederationservicetypes.v1_0.UpdateResponse;
import ch.mobi.xml.datatype.common.commons.v3.CallContext;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MaiaAmwFederationPortType", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/MaiaAmwFederationService/v1_0")
@XmlSeeAlso({
    ch.mobi.xml.datatype.ch.mobi.maia.amw.maiaamwfederation.v1_0.ObjectFactory.class,
    ch.mobi.xml.datatype.ch.mobi.maia.amw.maiaamwfederationservicetypes.v1_0.ObjectFactory.class,
    ch.mobi.xml.datatype.common.commons.v3.ObjectFactory.class,
    ch.mobi.xml.service.ch.mobi.maia.amw.v1_0.maiaamwfederationservice.datatype.ObjectFactory.class
})
public interface MaiaAmwFederationPortType {


    /**
     * 
     * @param update
     * @param callContext
     * @param fcOwner
     * @return
     *     returns ch.mobi.xml.datatype.ch.mobi.maia.amw.maiaamwfederationservicetypes.v1_0.UpdateResponse
     * @throws ValidationException
     * @throws TechnicalException
     * @throws BusinessException
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/v1_0/MaiaAmwFederationService/datatype", className = "ch.mobi.xml.service.ch.mobi.maia.amw.v1_0.maiaamwfederationservice.datatype.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/v1_0/MaiaAmwFederationService/datatype", className = "ch.mobi.xml.service.ch.mobi.maia.amw.v1_0.maiaamwfederationservice.datatype.UpdateResponse")
    public UpdateResponse update(
        @WebParam(name = "callContext", targetNamespace = "")
        CallContext callContext,
        @WebParam(name = "fcOwner", targetNamespace = "")
        String fcOwner,
        @WebParam(name = "update", targetNamespace = "")
        UpdateRequest update)
        throws BusinessException, TechnicalException, ValidationException
    ;

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "ping", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/v1_0/MaiaAmwFederationService/datatype", className = "ch.mobi.xml.service.ch.mobi.maia.amw.v1_0.maiaamwfederationservice.datatype.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/v1_0/MaiaAmwFederationService/datatype", className = "ch.mobi.xml.service.ch.mobi.maia.amw.v1_0.maiaamwfederationservice.datatype.PingResponse")
    public void ping();

}
