
package ch.mobi.xml.service.ch.mobi.maia.amw.maiaamwfederationservice.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TechnicalException", targetNamespace = "http://xml.mobi.ch/service/ch/mobi/maia/amw/v1_0/MaiaAmwFederationService/datatype")
public class TechnicalException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ch.mobi.xml.datatype.common.commons.v3.TechnicalException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public TechnicalException(String message, ch.mobi.xml.datatype.common.commons.v3.TechnicalException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public TechnicalException(String message, ch.mobi.xml.datatype.common.commons.v3.TechnicalException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ch.mobi.xml.datatype.common.commons.v3.TechnicalException
     */
    public ch.mobi.xml.datatype.common.commons.v3.TechnicalException getFaultInfo() {
        return faultInfo;
    }

}
